/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Header = {
  [k: string]: unknown;
} & {
  left?: HeaderItem;
  centre?: HeaderItem;
  right?: HeaderItem;
  /**
   * Whether to display the header.
   */
  visible?: boolean;
};
export type HeaderItem =
  | {
      type?: "logo";
      [k: string]: unknown;
    }
  | {
      type?: "menu";
      menu: Menu;
      [k: string]: unknown;
    };
export type Menu = {
  label: string;
  link: string;
  [k: string]: unknown;
}[];
export type Section = Hero;

/**
 * The schema for a Bare Site.
 */
export interface BareSite {
  /**
   * The version of the Bare Site schema used by this site.
   */
  schemaVersion: 1;
  /**
   * The name of the site (business, organisation, etcetera).
   */
  name: string;
  /**
   * A short description of the site.
   */
  description?: string;
  template: BareTemplate;
  theme: BareTheme;
  [k: string]: unknown;
}
/**
 * The schema for a Bare Site template.
 */
export interface BareTemplate {
  /**
   * The version of the Bare Site template schema used by this template
   */
  schemaVersion: 1;
  header: Header;
  footer: Footer;
  /**
   * @minItems 1
   */
  pages: [Page, ...Page[]];
  [k: string]: unknown;
}
export interface Footer {
  /**
   * Whether to display the footer.
   */
  visible?: boolean;
  [k: string]: unknown;
}
export interface Page {
  /**
   * The route of the page.
   */
  route: string;
  /**
   * The title of the page.
   */
  title: string;
  sections: Section[];
  [k: string]: unknown;
}
export interface Hero {
  type: "hero";
  image: string;
  heading: string;
  subheading?: string;
  actions?: Action[];
  [k: string]: unknown;
}
export interface Action {
  label: string;
  link: string;
  style?: "primary" | "secondary";
  [k: string]: unknown;
}
/**
 * The schema for a Bare Site theme.
 */
export interface BareTheme {
  /**
   * The version of the Bare Site theme schema used by this theme.
   */
  schemaVersion: 1;
  colours: Colours;
  typography: Typography;
  /**
   * The overall spacing density of the site.
   */
  spacing: "tight" | "comfortable" | "spacious";
  /**
   * The overall shape language of the site.
   */
  shape: "sharp" | "soft" | "rounded";
  [k: string]: unknown;
}
export interface Colours {
  /**
   * The main colour of your brand.
   */
  primary: string;
  /**
   * Foreground colour to use with the primary colour.
   */
  primaryContent: string;
  /**
   * The optional, secondary colour of your brand.
   */
  secondary?: string;
  /**
   * Foreground colour to use with the secondary colour.
   */
  secondaryContent?: string;
  /**
   * The optional, accent colour of your brand.
   */
  accent?: string;
  /**
   * Foreground colour to use with the accent color.
   */
  accentContent?: string;
  /**
   * A neutral dark colour.
   */
  neutral: string;
  /**
   * Foreground colour to use with the neutral color.
   */
  neutralContent: string;
  /**
   * Base surface colour.
   */
  base1: string;
  /**
   * Darker base colour.
   */
  base2: string;
  /**
   * Darkest base colour.
   */
  base3: string;
  /**
   * Foreground colour to use with the base colours.
   */
  baseContent: string;
  /**
   * Info colour.
   */
  info: string;
  /**
   * Foreground colour to use with the info colour.
   */
  infoContent: string;
  /**
   * Success colour.
   */
  success: string;
  /**
   * Foreground colour to use with the success colour.
   */
  successContent: string;
  /**
   * Warning colour.
   */
  warning: string;
  /**
   * Foreground colour to use with the warning colour.
   */
  warningContent: string;
  /**
   * Error colour.
   */
  error: string;
  /**
   * Foreground colour to use with the error colour.
   */
  errorContent: string;
  [k: string]: unknown;
}
export interface Typography {
  /**
   * The primary font used for headings.
   */
  heading: string;
  /**
   * The primary font used for body text.
   */
  body: string;
  [k: string]: unknown;
}
