/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Header = {
  [k: string]: unknown;
} & {
  left?: HeaderSection;
  centre?: HeaderSection1;
  right?: HeaderSection2;
  /**
   * Whether to display the header.
   */
  visible?: boolean;
};
/**
 * The left section of the header.
 */
export type HeaderSection =
  | {
      type?: "logo";
      [k: string]: unknown;
    }
  | {
      type?: "menu";
      menu: Menu;
      [k: string]: unknown;
    };
export type Menu = {
  label: string;
  link: string;
  [k: string]: unknown;
}[];
/**
 * The centre section of the header.
 */
export type HeaderSection1 =
  | {
      type?: "logo";
      [k: string]: unknown;
    }
  | {
      type?: "menu";
      menu: Menu;
      [k: string]: unknown;
    };
/**
 * The right section of the header.
 */
export type HeaderSection2 =
  | {
      type?: "logo";
      [k: string]: unknown;
    }
  | {
      type?: "menu";
      menu: Menu;
      [k: string]: unknown;
    };
