/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Header = {
  [k: string]: unknown;
} & {
  left?: HeaderItem;
  centre?: HeaderItem;
  right?: HeaderItem;
  /**
   * Whether to display the header.
   */
  visible?: boolean;
};
export type HeaderItem =
  | {
      type?: "logo";
      [k: string]: unknown;
    }
  | {
      type?: "menu";
      menu: Menu;
      [k: string]: unknown;
    };
export type Menu = {
  label: string;
  link: string;
  [k: string]: unknown;
}[];
