/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface Hero {
  type: "hero";
  image: string;
  heading: string;
  subheading?: string;
  actions?: Action[];
  [k: string]: unknown;
}
export interface Action {
  label: string;
  link: string;
  style?: "primary" | "secondary";
  [k: string]: unknown;
}
